FirmawareUploder Process with StreamGobblerThred exemple.
MarginallyClever/Makelangelo-software pull request #405
Opened 2021-12-25 01:09 UTC by PPAC37

From an old project of my ( to review but working)

Only for non interactive commands.

The kye is in the StreamGobbler (threaded object) as process err stream can be interlaced with  process out stream.

To adatapt to the needs.

2021-12-25 11:49 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +				   System.err.println("Cannot find nearby avrdude.conf ");
please use `Log.error` or later if #402 `logger.error`

2021-12-25 11:50 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +	public static SimpleDateFormat simpleDateFormat = new SimpleDateFormat("ddMMyyyy hh:mm:ss");
SimpleDateFormat is not thread safe thus must be reinstancited each you need it

2021-12-25 11:51 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +		System.out.printf("Running : ");
`Log.message()` for every message

2021-12-25 11:51 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +	    for (String arg : cmdArray) {
duplicate from above ?

2021-12-25 11:52 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +		Date dStar = new Date();
indentation : in your IDE, you should use the format feature.

2021-12-25 11:54 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +		    streamGobblerProcessIn = new StreamGobblerReadLineBufferedSpecial(process.getInputStream(), "out") {
I think the flash process should not ask anything to the user thus capturing the inputstream seems not necessary, what do you think ?

2021-12-25 11:54 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +		    lastExecSucces = true;
```suggestion
		    lastExecSucces = ret == 0;
```

2021-12-25 11:55 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/firmwareUploader/FirmwareUploader.java
> +		res.append(e.getMessage());
The full stack trace is missing

2021-12-25 11:59 UTC, coliss86 requested changes
Good job !
The indentation of the code is not correct, make it hard to read.
A lot of comments indicate that it is not finished and it cannot be merged. You should mark the PR as Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/

2021-12-25 16:20 UTC, PPAC37 commented
Thank you.

I close this PR to make a draft PR immediately!

I take note of all the comments. My apologies if I do not correct this immediately. (I take advantage of the holiday season with the family.)

And maybe i should wait for you PR https://github.com/MarginallyClever/Makelangelo-software/pull/402  to be finish and  merged.

Good continuation, and happy holidays.

2021-12-25 16:20 UTC, closed without merging

2021-12-25 17:16 UTC, coliss86 commented
No don't close :)
You can change the status of this PR (I think) or at least, you can edit the title to "DRAFT:"

2021-12-26 04:36 UTC, PPAC37 commented
Sorry I closed the PR!
 (I'm starting on github and haven't figured out how to pass an open PR into a PR project yet ... I only found the solution to close it and make one new but this time in draft. https://github.com/MarginallyClever/Makelangelo-software/pull/406 )