save only the portion of the drawing shown by the range slider. (#625)
MarginallyClever/Makelangelo-software pull request #631
Opened 2022-03-25 22:54 UTC by i-make-robots

for #625

Tested on stanford bunny, seems fine.
Tested on a jpeg.  Correct gcode, but loading gcode into the app smashes all colors to black.
Turtles might want to generate a comment after M0 with the hex value of the color.

2022-03-26 10:37 UTC, coliss86 requested changes
Remove the static values and add units tests please

2022-03-26 10:37 UTC, coliss86 commented on src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
> +		SaveGCode.setTrimHead(bottom);
Settings static values in the a bad pattern. Every time the user ask to save the gcode, a new `SaveGCode` is instanciated, so thoses values can be set in the constructor of even better in the `save()` method

2022-03-26 17:33 UTC, i-make-robots commented
Show me an elegant way to remove the static variable. I did want it, either.

> On Mar 26, 2022, at 3:37 AM, coliss86 ***@***.***> wrote:
> 
> ﻿
> @coliss86 requested changes on this pull request.
> 
> Remove the static values and add units tests please
> 
> In src/main/java/com/marginallyclever/makelangelo/Makelangelo.java:
> 
> > @@ -876,6 +877,8 @@ private void onChangeSlider(ChangeEvent e) {
>          myTurtleRenderer.setLast(top);
>          labelRangeMin.setText(Integer.toString(bottom));
>          labelRangeMax.setText(Integer.toString(top));
> +		SaveGCode.setTrimHead(bottom);
> Settings static values in the a bad pattern. Every time the user ask to save the gcode, a new SaveGCode is instanciated, so thoses values can be set in the constructor of even better in the save() method
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-03-26 18:43 UTC, coliss86 commented
Here is : https://github.com/MarginallyClever/Makelangelo-software/pull/632

2022-03-28 07:27 UTC, coliss86 approved these changes
LGTM

2022-03-28 17:48 UTC, merged